### ISSUE TITLE
Chapter Logo

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/costarica#2]
Do you have a chapter logo?

https://github.com/nodeschool/international-day/issues/86

**Comment by gaboesquivel** [comment]
use this one in the mean time https://infinit.io/_/jBZJrNa

**Comment by gaboesquivel** [comment]
please share logo proposals here @cayasso @kevinblanco
when we have the final one we need to add it to http://nodeschool.io/hexdex.html

**Comment by smoothness** [comment]
We are working on a new proposal. I will post it as soon as we have it done.

**Comment by cayasso** [comment]
![nodeschoolcrtresrios2](https://cloud.githubusercontent.com/assets/42518/14122315/7d755608-f5b8-11e5-9998-9caaa150b40f.png)

**Comment by smoothness** [comment]
![cr-hexagon](https://cloud.githubusercontent.com/assets/2099833/14146889/8a39a9cc-f656-11e5-919c-22043d8fd7fe.png)

**Comment by smoothness** [comment]
![hex-cr](https://cloud.githubusercontent.com/assets/2099833/14147226/c5d7f80c-f657-11e5-8355-7b79c7f10475.png)

**Comment by avenidanet** [comment]
Vamos a trabajar en una propuesta también. PV

**Comment by avenidanet** [comment]
Acá nuestra propuesta (la del perezoso es la que me gusta)
![nodeschool-costarica](https://cloud.githubusercontent.com/assets/1860889/14262814/a252ce2c-fa74-11e5-832e-bddd12209226.png)

**Comment by gaboesquivel** [comment]
yo me quedo con la del perezoso :+1:  :)

**Comment by steven-perez** [comment]
perezoso :+1:

**Comment by jarias** [comment]
perezoso :+1:  pero no debería ser CRI en lugar de CRC, CRI es codigo ISO de Costa Rica CRC es el de la moneda.

**Comment by gaboesquivel** [comment]
o SJO  para San Jose

**Comment by avenidanet** [comment]
Con las anotaciones [nodeschool-costarica-1.pdf](https://github.com/nodeschool/costarica/files/209305/nodeschool-costarica-1.pdf)

**Comment by yeco** [comment]
Perezoso.

**Comment by laubits** [comment]
El oso

**Comment by gaboesquivel** [comment]
@avenidanet  podrías subir un png del perezoso con CRI o SJO aquí ?   únicamente el perezoso

**Comment by avenidanet** [comment]
Claro, 
![oso](https://cloud.githubusercontent.com/assets/1860889/14463816/cb8e6d26-0089-11e6-959a-9c1730bd5a90.png)

Igual en un comentario anterior está el PDF, que es el editable.

Pura vida.

**Comment by gaboesquivel** [comment]
excelente! :)

**Comment by gaboesquivel** [comment]
thanks!
