### ISSUE TITLE
improve the design

### ISSUE THREAD

**Issue by gaboesquivel** [nodeschool/costarica#5]
the site needs some love

**Comment by rubenabix** [comment]
Adding margins.
Adjust the width of the video.
Adjust paragraphs.

![0](https://cloud.githubusercontent.com/assets/13205620/14114541/92426626-f594-11e5-9286-13ead5ac7e43.png)

![1](https://cloud.githubusercontent.com/assets/13205620/14114689/354c7d34-f595-11e5-8622-9653d9ccb299.png)

![2](https://cloud.githubusercontent.com/assets/13205620/14114691/396b4b8e-f595-11e5-9664-4824e8c3a1fa.png)

**Comment by gaboesquivel** [comment]
si @rubenabix  por favor arreglar los estilos para móviles

**Comment by gaboesquivel** [comment]
@avenidanet  no puedo asignarte esto, aun tienes que aceptar la invitación https://github.com/nodeschool/costarica/issues/7  para poder hacerlo

**Comment by gaboesquivel** [comment]
done
